services:
  db:
    image: bitnami/postgresql:latest
    container_name: brevly
    restart: unless-stopped
    ports:
      - 5432:$POSTGRES_PORT
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - db:/var/lib/postgresql/data


volumes:
  db:
    driver: local
